quarkus.datasource.db-kind=mysql
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/cliente_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
quarkus.datasource.username=cliente_user
quarkus.datasource.password=${USER_DATASOURCE_PASSWORD:secure_password_cliente}
quarkus.datasource.jdbc.driver=com.mysql.cj.jdbc.Driver

quarkus.hibernate-orm.log.sql=true

quarkus.flyway.locations=classpath:db
quarkus.flyway.create-schemas=true
quarkus.flyway.baseline-on-migrate=true
quarkus.log.category."org.flywaydb".level=DEBUG

quarkus.application.name=tech-challenge-4a-fase_cliente_quarkus
quarkus.http.port=9090